### ISSUE TITLE
How to add elements to NavBar?

### ISSUE THREAD

**Issue by ghost** [RinteRface/argonDash#3]
Hi, I am trying to create a page with the a horizontal navbar on top. I tried setting `vertical=FALSE` in `argonDashSidebar` but the items are displayed under each other not side by side. 

I think having a top navbar to navigate between the different app pages is a crucial aspect of a Shiny app. Thanks for any help!

**Comment by DivadNojnarg** [comment]
Hi,

Indeed. Compared to the original template, argonDash sidebar items do not have the same class as the original template since I needed a special class to trigger tabs in the body (namely nav-pills). This explains why they don't behave as expected when vertical is set to FALSE. 

I will push an easy fix tonight. 

I will implement a feature as in vanilla shiny to make it cleaner. This will take more time however.
